name: ci
on:
  push: {branches: [ main ]}
  pull_request: {branches: [ main ]}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv && source .venv/bin/activate && pip install -U pip && pip install -e .
      - run: python -c "import evdemand; print('ok')"
